export interface ProfileData {
  income: string;
  occupation: string;
  technology: string;
  country: string;
  state: string;
}

export const countries = [
  { name: "United States", code: "US" },
  { name: "Germany", code: "DE" },
  { name: "Canada", code: "CA" },
  { name: "United Kingdom", code: "GB" },
  { name: "Russia", code: "RU" },
  { name: "France", code: "FR" },
];

export const states: { [country: string]: { name: string; code: string }[] } = {
  "United States": [
    { name: "Alabama", code: "AL" },
    { name: "Alaska", code: "AK" },
    { name: "Arizona", code: "AZ" },
    { name: "Arkansas", code: "AR" },
    { name: "California", code: "CA" },
    { name: "Colorado", code: "CO" },
    { name: "Connecticut", code: "CT" },
    { name: "Delaware", code: "DE" },
    { name: "Florida", code: "FL" },
    { name: "Georgia", code: "GA" },
    { name: "Hawaii", code: "HI" },
    { name: "Idaho", code: "ID" },
    { name: "Illinois", code: "IL" },
    { name: "Indiana", code: "IN" },
    { name: "Iowa", code: "IA" },
    { name: "Kansas", code: "KS" },
    { name: "Kentucky", code: "KY" },
    { name: "Louisiana", code: "LA" },
    { name: "Maine", code: "ME" },
    { name: "Maryland", code: "MD" },
    { name: "Massachusetts", code: "MA" },
    { name: "Michigan", code: "MI" },
    { name: "Minnesota", code: "MN" },
    { name: "Mississippi", code: "MS" },
    { name: "Missouri", code: "MO" },
    { name: "Montana", code: "MT" },
    { name: "Nebraska", code: "NE" },
    { name: "Nevada", code: "NV" },
    { name: "New Hampshire", code: "NH" },
    { name: "New Jersey", code: "NJ" },
    { name: "New Mexico", code: "NM" },
    { name: "New York", code: "NY" },
    { name: "North Carolina", code: "NC" },
    { name: "North Dakota", code: "ND" },
    { name: "Ohio", code: "OH" },
    { name: "Oklahoma", code: "OK" },
    { name: "Oregon", code: "OR" },
    { name: "Pennsylvania", code: "PA" },
    { name: "Rhode Island", code: "RI" },
    { name: "South Carolina", code: "SC" },
    { name: "South Dakota", code: "SD" },
    { name: "Tennessee", code: "TN" },
    { name: "Texas", code: "TX" },
    { name: "Utah", code: "UT" },
    { name: "Vermont", code: "VT" },
    { name: "Virginia", code: "VA" },
    { name: "Washington", code: "WA" },
    { name: "West Virginia", code: "WV" },
    { name: "Wisconsin", code: "WI" },
    { name: "Wyoming", code: "WY" },
  ],
  "Germany": [
    { name: "Baden-Württemberg", code: "BW" },
    { name: "Bavaria", code: "BY" },
    { name: "Berlin", code: "BE" },
    { name: "Brandenburg", code: "BB" },
    { name: "Bremen", code: "HB" },
    { name: "Hamburg", code: "HH" },
    { name: "Hesse", code: "HE" },
    { name: "Lower Saxony", code: "NI" },
    { name: "Mecklenburg-Vorpommern", code: "MV" },
    { name: "North Rhine-Westphalia", code: "NW" },
    { name: "Rhineland-Palatinate", code: "RP" },
    { name: "Saarland", code: "SL" },
    { name: "Saxony", code: "SN" },
    { name: "Saxony-Anhalt", code: "ST" },
    { name: "Schleswig-Holstein", code: "SH" },
    { name: "Thuringia", code: "TH" },
  ],
  "Canada": [
    { name: "Alberta", code: "AB" },
    { name: "British Columbia", code: "BC" },
    { name: "Manitoba", code: "MB" },
    { name: "New Brunswick", code: "NB" },
    { name: "Newfoundland and Labrador", code: "NL" },
    { name: "Nova Scotia", code: "NS" },
    { name: "Ontario", code: "ON" },
    { name: "Prince Edward Island", code: "PE" },
    { name: "Quebec", code: "QC" },
    { name: "Saskatchewan", code: "SK" },
    { name: "Northwest Territories", code: "NT" },
    { name: "Nunavut", code: "NU" },
    { name: "Yukon", code: "YT" },
  ],
  "United Kingdom": [
    { name: "England", code: "ENG" },
    { name: "Scotland", code: "SCT" },
    { name: "Wales", code: "WLS" },
    { name: "Northern Ireland", code: "NIR" },
  ],
  "Russia": [
    { name: "Altai Krai", code: "ALT" },
    { name: "Amur Oblast", code: "AMU" },
    { name: "Arkhangelsk Oblast", code: "ARK" },
    { name: "Astrakhan Oblast", code: "AST" },
    { name: "Belgorod Oblast", code: "BEL" },
    { name: "Bryansk Oblast", code: "BRY" },
    { name: "Chelyabinsk Oblast", code: "CHE" },
    { name: "Irkutsk Oblast", code: "IRK" },
    { name: "Ivanovo Oblast", code: "IVA" },
    { name: "Kaliningrad Oblast", code: "KGD" },
    { name: "Kaluga Oblast", code: "KLU" },
    { name: "Kamchatka Krai", code: "KAM" },
    { name: "Kemerovo Oblast", code: "KEM" },
    { name: "Khabarovsk Krai", code: "KHA" },
    { name: "Kirov Oblast", code: "KIR" },
    { name: "Kostroma Oblast", code: "KOS" },
    { name: "Krasnodar Krai", code: "KDA" },
    { name: "Krasnoyarsk Krai", code: "KYA" },
    { name: "Kurgan Oblast", code: "KGN" },
    { name: "Kursk Oblast", code: "KRS" },
    { name: "Leningrad Oblast", code: "LEN" },
    { name: "Lipetsk Oblast", code: "LIP" },
    { name: "Magadan Oblast", code: "MAG" },
    { name: "Moscow", code: "MOW" },
    { name: "Moscow Oblast", code: "MOS" },
    { name: "Murmansk Oblast", code: "MUR" },
    { name: "Nizhny Novgorod Oblast", code: "NIZ" },
    { name: "Novgorod Oblast", code: "NGR" },
    { name: "Novosibirsk Oblast", code: "NVS" },
    { name: "Omsk Oblast", code: "OMS" },
    { name: "Orenburg Oblast", code: "ORE" },
    { name: "Oryol Oblast", code: "ORL" },
    { name: "Penza Oblast", code: "PNZ" },
    { name: "Perm Krai", code: "PER" },
    { name: "Primorsky Krai", code: "PRI" },
    { name: "Pskov Oblast", code: "PSK" },
    { name: "Rostov Oblast", code: "ROS" },
    { name: "Ryazan Oblast", code: "RYA" },
    { name: "Saint Petersburg", code: "SPE" },
    { name: "Sakhalin Oblast", code: "SAK" },
    { name: "Samara Oblast", code: "SAM" },
    { name: "Saratov Oblast", code: "SAR" },
    { name: "Smolensk Oblast", code: "SMO" },
    { name: "Stavropol Krai", code: "STA" },
    { name: "Sverdlovsk Oblast", code: "SVE" },
    { name: "Tambov Oblast", code: "TAM" },
    { name: "Tomsk Oblast", code: "TOM" },
    { name: "Tula Oblast", code: "TUL" },
    { name: "Tver Oblast", code: "TVE" },
    { name: "Tyumen Oblast", code: "TYU" },
    { name: "Ulyanovsk Oblast", code: "ULY" },
    { name: "Vladimir Oblast", code: "VLA" },
    { name: "Volgograd Oblast", code: "VGG" },
    { name: "Vologda Oblast", code: "VLG" },
    { name: "Voronezh Oblast", code: "VOR" },
    { name: "Yaroslavl Oblast", code: "YAR" },
    { name: "Zabaykalsky Krai", code: "ZAB" },
  ],
  "France": [
    { name: "Auvergne-Rhône-Alpes", code: "ARA" },
    { name: "Bourgogne-Franche-Comté", code: "BFC" },
    { name: "Brittany", code: "BRE" },
    { name: "Centre-Val de Loire", code: "CVL" },
    { name: "Corsica", code: "COR" },
    { name: "Grand Est", code: "GES" },
    { name: "Hauts-de-France", code: "HDF" },
    { name: "Île-de-France", code: "IDF" },
    { name: "Normandy", code: "NOR" },
    { name: "Nouvelle-Aquitaine", code: "NAQ" },
    { name: "Occitanie", code: "OCC" },
    { name: "Pays de la Loire", code: "PDL" },
    { name: "Provence-Alpes-Côte d'Azur", code: "PAC" },
  ],
};
